#include "tester/tester.h"
#include "src/vec-sol.c"
// This file was autogenerated

static test t("2\n\n5\n\n1 2 3 4 5.5\n\n6 5 2 7.5 3\n\n\n\n\n\n\n\n\n\n                                           2","7.00 7.00 5.00 11.50 8.50");